#!/bin/bash
# Copies the motion engine to the website. brand-motion/ is the source; the site copy is generated.
# Usage: bash brand-motion/sync-site.sh
set -e
HERE="$(cd "$(dirname "$0")" && pwd)"
OUT="$HERE/../prototype/kreated-v2/assets/motion"
mkdir -p "$OUT"
{ echo "/* GENERATED by brand-motion/sync-site.sh from kmotion.js + kmotion-color.js + kmotion-services.js. Do not edit here. */"
  cat "$HERE/kmotion.js" "$HERE/kmotion-color.js" "$HERE/kmotion-services.js"; } > "$OUT/kmotion.js"
{ echo "/* GENERATED by brand-motion/sync-site.sh from kplayer.js. Do not edit here. */"; cat "$HERE/kplayer.js"; } > "$OUT/kplayer.js"
wc -c "$OUT"/*.js
